package calendar

import (
	"errors"
	"strings"
	"time"
)

var ErrNotFound = errors.New("event not found")

// EventInput is the user-editable part of an Event: what the frontend's
// event form sends for both creating and editing. Everything else on Event
// (ID, CreatedAt, Exceptions, Completions) is owned by the Service.
type EventInput struct {
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Location    string          `json:"location"`
	Start       time.Time       `json:"start"`
	End         time.Time       `json:"end"`
	AllDay      bool            `json:"allDay"`
	Important   bool            `json:"important"`
	Recurrence  *RecurrenceRule `json:"recurrence,omitempty"`
	// ReminderLeadSeconds lists how long before each occurrence a reminder
	// fires (0 = at the start time).
	ReminderLeadSeconds []int `json:"reminderLeadSeconds"`
}

// normalized returns a validated copy of in, with every time moved to
// time.Local. Times arrive from the frontend as UTC; recurrence expansion
// works on the anchor's own calendar fields (weekday, day of month), so it
// has to run in the user's zone or a 9pm Monday event expands as Tuesday.
func (in EventInput) normalized() (EventInput, error) {
	in.Title = strings.TrimSpace(in.Title)
	if in.Title == "" {
		return in, errors.New("title is required")
	}

	in.Start = in.Start.In(time.Local)
	in.End = in.End.In(time.Local)
	if in.End.Before(in.Start) {
		return in, errors.New("end must not be before start")
	}

	for _, lead := range in.ReminderLeadSeconds {
		if lead < 0 {
			return in, errors.New("reminder lead time must not be negative")
		}
	}

	if in.Recurrence != nil {
		rule := *in.Recurrence

		switch rule.Frequency {
		case FrequencyDaily, FrequencyWeekly, FrequencyMonthly, FrequencyYearly:
		default:
			return in, errors.New("unknown repeat frequency")
		}

		if rule.Interval <= 0 {
			rule.Interval = 1
		}
		if rule.Count < 0 {
			return in, errors.New("repeat count must not be negative")
		}
		if rule.Count > 0 && rule.Until != nil {
			return in, errors.New("repeat can end after a count or on a date, not both")
		}
		if rule.Until != nil {
			until := rule.Until.In(time.Local)
			if until.Before(in.Start) {
				return in, errors.New("repeat end date must not be before the start")
			}
			rule.Until = &until
		}

		if len(rule.Weekdays) > 0 && rule.Frequency != FrequencyWeekly {
			return in, errors.New("weekdays only apply to weekly repeats")
		}
		for _, d := range rule.Weekdays {
			if d < time.Sunday || d > time.Saturday {
				return in, errors.New("invalid weekday")
			}
		}

		in.Recurrence = &rule
	}

	return in, nil
}

// Event is a single scheduled item, optionally repeating via Recurrence.
// For a repeating event, Start/End describe the first occurrence; later
// occurrences are generated by Occurrences and reuse the same duration.
type Event struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description,omitempty"`
	Location    string    `json:"location,omitempty"`
	Start       time.Time `json:"start"`
	End         time.Time `json:"end"`
	AllDay      bool      `json:"allDay"`
	// Important marks an event for emphasis in compact views (e.g. a red dot
	// on a month grid) — a birthday vs. a routine garbage-day reminder.
	Important   bool            `json:"important"`
	Recurrence  *RecurrenceRule `json:"recurrence,omitempty"`
	Exceptions  []Exception     `json:"exceptions,omitempty"`
	Reminders   []Reminder      `json:"reminders,omitempty"`
	Completions []Completion    `json:"completions,omitempty"`
	CreatedAt   time.Time       `json:"createdAt"`
}

// ExceptionType identifies how an Exception overrides a single occurrence.
type ExceptionType string

const (
	// ExceptionSkip removes the occurrence entirely (e.g. "no garbage pickup
	// this week because of the holiday").
	ExceptionSkip ExceptionType = "skip"
	// ExceptionReschedule moves the occurrence to a new start (and optionally
	// end) time instead of removing it.
	ExceptionReschedule ExceptionType = "reschedule"
)

// Exception overrides a single generated occurrence of a recurring event.
// OriginalDate identifies which occurrence to override by matching its
// calendar date (year/month/day, in the event's own location) against the
// raw, un-overridden occurrence date produced by the recurrence rule.
type Exception struct {
	OriginalDate time.Time     `json:"originalDate"`
	Type         ExceptionType `json:"type"`
	// NewStart is required when Type is ExceptionReschedule.
	NewStart *time.Time `json:"newStart,omitempty"`
	// NewEnd is optional when Type is ExceptionReschedule; if omitted, the
	// occurrence keeps its original duration relative to NewStart.
	NewEnd *time.Time `json:"newEnd,omitempty"`
}

// Completion marks a specific occurrence of an event as done — e.g. "took
// the garbage out this Thursday". Matched to an occurrence the same way
// Exception is: by calendar date against the occurrence's raw, un-rescheduled
// date, so it still applies even if that occurrence was later rescheduled.
type Completion struct {
	OccurrenceDate time.Time `json:"occurrenceDate"`
	CompletedAt    time.Time `json:"completedAt"`
}

// Occurrence is one concrete instance of an Event, after recurrence
// expansion and any Exception has been applied.
type Occurrence struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
	// OriginalStart is the raw, un-overridden occurrence date the recurrence
	// rule produced for this slot, even if an Exception rescheduled it. It's
	// a stable key for matching an occurrence back to its Exception or
	// Completion (or for creating a new one).
	OriginalStart time.Time `json:"originalStart"`
	Done          bool      `json:"done"`
}

// OccurrenceView pairs an expanded Occurrence with the Event it belongs to.
// It's what the service hands to the frontend for date-ranged views (the
// upcoming-events widget, the month grid) so the frontend never has to
// re-derive recurrence itself.
type OccurrenceView struct {
	Occurrence
	EventID     string `json:"eventId"`
	Title       string `json:"title"`
	Description string `json:"description,omitempty"`
	Location    string `json:"location,omitempty"`
	AllDay      bool   `json:"allDay"`
	Important   bool   `json:"important"`
	Recurring   bool   `json:"recurring"`
}

func sameCalendarDate(a, b time.Time) bool {
	ay, am, ad := a.In(a.Location()).Date()
	by, bm, bd := b.In(a.Location()).Date()
	return ay == by && am == bm && ad == bd
}
