package calendar

import (
	"errors"
	"time"
)

var ErrNotFound = errors.New("event not found")

// Event is a single scheduled item, optionally repeating via Recurrence.
// For a repeating event, Start/End describe the first occurrence; later
// occurrences are generated by Occurrences and reuse the same duration.
type Event struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description,omitempty"`
	Location    string    `json:"location,omitempty"`
	Start       time.Time `json:"start"`
	End         time.Time `json:"end"`
	AllDay      bool      `json:"allDay"`
	// Important marks an event for emphasis in compact views (e.g. a red dot
	// on a month grid) — a birthday vs. a routine garbage-day reminder.
	Important   bool            `json:"important"`
	Recurrence  *RecurrenceRule `json:"recurrence,omitempty"`
	Exceptions  []Exception     `json:"exceptions,omitempty"`
	Reminders   []Reminder      `json:"reminders,omitempty"`
	Completions []Completion    `json:"completions,omitempty"`
	CreatedAt   time.Time       `json:"createdAt"`
}

// ExceptionType identifies how an Exception overrides a single occurrence.
type ExceptionType string

const (
	// ExceptionSkip removes the occurrence entirely (e.g. "no garbage pickup
	// this week because of the holiday").
	ExceptionSkip ExceptionType = "skip"
	// ExceptionReschedule moves the occurrence to a new start (and optionally
	// end) time instead of removing it.
	ExceptionReschedule ExceptionType = "reschedule"
)

// Exception overrides a single generated occurrence of a recurring event.
// OriginalDate identifies which occurrence to override by matching its
// calendar date (year/month/day, in the event's own location) against the
// raw, un-overridden occurrence date produced by the recurrence rule.
type Exception struct {
	OriginalDate time.Time     `json:"originalDate"`
	Type         ExceptionType `json:"type"`
	// NewStart is required when Type is ExceptionReschedule.
	NewStart *time.Time `json:"newStart,omitempty"`
	// NewEnd is optional when Type is ExceptionReschedule; if omitted, the
	// occurrence keeps its original duration relative to NewStart.
	NewEnd *time.Time `json:"newEnd,omitempty"`
}

// Completion marks a specific occurrence of an event as done — e.g. "took
// the garbage out this Thursday". Matched to an occurrence the same way
// Exception is: by calendar date against the occurrence's raw, un-rescheduled
// date, so it still applies even if that occurrence was later rescheduled.
type Completion struct {
	OccurrenceDate time.Time `json:"occurrenceDate"`
	CompletedAt    time.Time `json:"completedAt"`
}

// Occurrence is one concrete instance of an Event, after recurrence
// expansion and any Exception has been applied.
type Occurrence struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
	// OriginalStart is the raw, un-overridden occurrence date the recurrence
	// rule produced for this slot, even if an Exception rescheduled it. It's
	// a stable key for matching an occurrence back to its Exception or
	// Completion (or for creating a new one).
	OriginalStart time.Time `json:"originalStart"`
	Done          bool      `json:"done"`
}

// OccurrenceView pairs an expanded Occurrence with the Event it belongs to.
// It's what the service hands to the frontend for date-ranged views (the
// upcoming-events widget, the month grid) so the frontend never has to
// re-derive recurrence itself.
type OccurrenceView struct {
	Occurrence
	EventID     string `json:"eventId"`
	Title       string `json:"title"`
	Description string `json:"description,omitempty"`
	Location    string `json:"location,omitempty"`
	AllDay      bool   `json:"allDay"`
	Important   bool   `json:"important"`
}

func sameCalendarDate(a, b time.Time) bool {
	ay, am, ad := a.In(a.Location()).Date()
	by, bm, bd := b.In(a.Location()).Date()
	return ay == by && am == bm && ad == bd
}
