// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEvent(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddEvent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AddHabit(arg1) {
  return window['go']['main']['App']['AddHabit'](arg1);
}

export function AddReminder(arg1, arg2) {
  return window['go']['main']['App']['AddReminder'](arg1, arg2);
}

export function AddTask(arg1, arg2) {
  return window['go']['main']['App']['AddTask'](arg1, arg2);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function DeleteHabit(arg1) {
  return window['go']['main']['App']['DeleteHabit'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDueReminders() {
  return window['go']['main']['App']['GetDueReminders']();
}

export function ListCalendarOccurrences(arg1, arg2) {
  return window['go']['main']['App']['ListCalendarOccurrences'](arg1, arg2);
}

export function ListEvents() {
  return window['go']['main']['App']['ListEvents']();
}

export function ListHabits() {
  return window['go']['main']['App']['ListHabits']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function RenameHabit(arg1, arg2) {
  return window['go']['main']['App']['RenameHabit'](arg1, arg2);
}

export function ToggleEventCompletion(arg1, arg2) {
  return window['go']['main']['App']['ToggleEventCompletion'](arg1, arg2);
}

export function ToggleHabitCompletion(arg1, arg2) {
  return window['go']['main']['App']['ToggleHabitCompletion'](arg1, arg2);
}

export function ToggleTask(arg1) {
  return window['go']['main']['App']['ToggleTask'](arg1);
}
