// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function ToggleTask(arg1) {
  return window['go']['main']['App']['ToggleTask'](arg1);
}
