// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEvent(arg1) {
  return window['go']['main']['App']['AddEvent'](arg1);
}

export function AddHabit(arg1) {
  return window['go']['main']['App']['AddHabit'](arg1);
}

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function AddProjectTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProjectTask'](arg1, arg2, arg3);
}

export function AddReminder(arg1, arg2) {
  return window['go']['main']['App']['AddReminder'](arg1, arg2);
}

export function AddTask(arg1, arg2) {
  return window['go']['main']['App']['AddTask'](arg1, arg2);
}

export function CompleteWorkout(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CompleteWorkout'](arg1, arg2, arg3, arg4);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function DeleteHabit(arg1) {
  return window['go']['main']['App']['DeleteHabit'](arg1);
}

export function DeleteJournalEntry(arg1) {
  return window['go']['main']['App']['DeleteJournalEntry'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDueReminders() {
  return window['go']['main']['App']['GetDueReminders']();
}

export function GetJobsInfo() {
  return window['go']['main']['App']['GetJobsInfo']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListCalendarOccurrences(arg1, arg2) {
  return window['go']['main']['App']['ListCalendarOccurrences'](arg1, arg2);
}

export function ListEvents() {
  return window['go']['main']['App']['ListEvents']();
}

export function ListHabits() {
  return window['go']['main']['App']['ListHabits']();
}

export function ListJobApplications() {
  return window['go']['main']['App']['ListJobApplications']();
}

export function ListJobQueue() {
  return window['go']['main']['App']['ListJobQueue']();
}

export function ListJournalEntries() {
  return window['go']['main']['App']['ListJournalEntries']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function ListWorkoutCycles() {
  return window['go']['main']['App']['ListWorkoutCycles']();
}

export function MarkJobApplied(arg1) {
  return window['go']['main']['App']['MarkJobApplied'](arg1);
}

export function MarkWeeklyReviewed() {
  return window['go']['main']['App']['MarkWeeklyReviewed']();
}

export function MoveTask(arg1, arg2) {
  return window['go']['main']['App']['MoveTask'](arg1, arg2);
}

export function RenameHabit(arg1, arg2) {
  return window['go']['main']['App']['RenameHabit'](arg1, arg2);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function RenameTask(arg1, arg2) {
  return window['go']['main']['App']['RenameTask'](arg1, arg2);
}

export function ResetWorkouts() {
  return window['go']['main']['App']['ResetWorkouts']();
}

export function SaveJournalEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveJournalEntry'](arg1, arg2, arg3);
}

export function SetJobQueueOutcome(arg1, arg2) {
  return window['go']['main']['App']['SetJobQueueOutcome'](arg1, arg2);
}

export function SetJobSearchDir(arg1) {
  return window['go']['main']['App']['SetJobSearchDir'](arg1);
}

export function SetTaskContexts(arg1, arg2) {
  return window['go']['main']['App']['SetTaskContexts'](arg1, arg2);
}

export function SetTaskProject(arg1, arg2) {
  return window['go']['main']['App']['SetTaskProject'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetupWorkouts(arg1, arg2) {
  return window['go']['main']['App']['SetupWorkouts'](arg1, arg2);
}

export function SkipEventOccurrence(arg1, arg2) {
  return window['go']['main']['App']['SkipEventOccurrence'](arg1, arg2);
}

export function ToggleEventCompletion(arg1, arg2) {
  return window['go']['main']['App']['ToggleEventCompletion'](arg1, arg2);
}

export function ToggleHabitCompletion(arg1, arg2) {
  return window['go']['main']['App']['ToggleHabitCompletion'](arg1, arg2);
}

export function ToggleProject(arg1) {
  return window['go']['main']['App']['ToggleProject'](arg1);
}

export function ToggleTask(arg1) {
  return window['go']['main']['App']['ToggleTask'](arg1);
}

export function UndoLastWorkout() {
  return window['go']['main']['App']['UndoLastWorkout']();
}

export function UpdateEvent(arg1, arg2) {
  return window['go']['main']['App']['UpdateEvent'](arg1, arg2);
}

export function UpdateWorkoutCycle(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateWorkoutCycle'](arg1, arg2, arg3);
}

export function UpdateWorkoutLog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateWorkoutLog'](arg1, arg2, arg3, arg4);
}
