// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {calendar} from '../models';
import {tasks} from '../models';
import {app} from '../models';

export function AddEvent(arg1:string,arg2:string,arg3:string,arg4:time.Time,arg5:time.Time,arg6:boolean,arg7:calendar.RecurrenceRule,arg8:boolean):Promise<calendar.Event>;

export function AddReminder(arg1:string,arg2:number):Promise<calendar.Event>;

export function AddTask(arg1:string,arg2:string):Promise<tasks.Task>;

export function DeleteEvent(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetAppInfo():Promise<app.Info>;

export function GetDueReminders():Promise<Array<calendar.DueReminder>>;

export function ListCalendarOccurrences(arg1:time.Time,arg2:time.Time):Promise<Array<calendar.OccurrenceView>>;

export function ListEvents():Promise<Array<calendar.Event>>;

export function ListTasks():Promise<Array<tasks.Task>>;

export function ToggleTask(arg1:string):Promise<tasks.Task>;
