// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tasks} from '../models';
import {app} from '../models';

export function AddTask(arg1:string):Promise<tasks.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetAppInfo():Promise<app.Info>;

export function ListTasks():Promise<Array<tasks.Task>>;

export function ToggleTask(arg1:string):Promise<tasks.Task>;
